### ISSUE TITLE
save_swin_features.py need mm serise but requirement.txt not contain mm serise dependency

### ISSUE THREAD

**Issue by waterself** [sinhasaptarshi/EveryShotCounts#7]
would you let me know
mmaction dependency(mmaction 1.x upper remove mmaction.model.build_model)
for run save_swim_features.py ?

**Comment by sinhasaptarshi** [comment]
We use mmaction 1.2.0

**Comment by waterself** [comment]
i try to Extract VideoMAE encodings to python save_swin_features.py --dataset RepCount --model VideoMAE --num_gpus 1 --data_path data/RepCount
but encounter error with import.
python save_swin_features.py --dataset RepCount --model VideoMAE --num_gpus 1 --data_path data/RepCount
Traceback (most recent call last):
  File "save_swin_features.py", line 6, in <module>
    from mmaction.models import build_model
ImportError: cannot import name 'build_model' from 'mmaction.models'

i install all requirements from pip isntall -r requirements.txt 
and mmaction2 and dependencies from docs.

Would you like to provide anything to solve the problem?

# Name                    Version                   Build  Channel
mmaction2                 1.2.0                    pypi_0    pypi
mmcv                      2.0.0                    pypi_0    pypi
mmdet                     3.0.0                    pypi_0    pypi
mmengine                  0.10.5                   pypi_0    pypi
mmpose                    1.0.0                    pypi_0    pypi
timm                      1.0.12                   pypi_0    pypi

**Comment by sinhasaptarshi** [comment]
We have updated the readme. Note that we updated the repo to contain the mmaction folder that we use. You dont need to install mmaction separately anymore. Just follow the installation commands given in the readme and it should work.

**Comment by waterself** [comment]
thanks for your great works!
save_swim_feature.py now works.
